name: 'depcheck Action'
description: 'List up libraries that are defined in dependencies and devDependencies in package.json but not used in your codes.'
author: 'tubone24'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  pr-comment-url:
    description: 'GitHub PR Comment URL'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
