name: 'depcheck Action'
description: 'List up libraries that are defined in dependencies and devDependencies in package.json but not used in your codes.'
author: 'tubone24'
runs:
  using: 'docker'
  image: 'Dockerfile'
